services:
  brother_ql_web:
    image: davidramiro/brother-ql-web:latest # latest online version
    # build: . # building locally from source (see git clone below))
    container_name: brother_ql_web
    restart: always
    ports:
      - "8013:8013"
#    devices:
#      - "/dev/usb/lp0:/dev/usb/lp0"
    command: >
      --model QL-800
      --default-label-size 62
      file:///dev/usb/lp0
